name:SA
on:
  push:
    branches:[master]
  pull-request:
    branches:[master]
jobs:
  myci:
    runs-on:ubuntu-latest
    steps:
    - uses:actions/checkout@v2
    - name:Set up k
      uses:actions/setup-go@v2
      with:
        go-version:1.16
    - name:Build
      run:go build -v
 
    
